# pnpm-workspace.yaml

packages:
  # Das '.' steht f체r das Haupt-Projekt (deine Next.js App)
  - '.'
  # Das hier ist dein Unter-Projekt f체r die Firebase Functions
  - 'firebase_functions'
  # Webmail-Proxy (l채uft auf Hetzner Server)
  - 'webmail-proxy'

# Fix f체r Dependency-Konflikte zwischen whatsapp-web.js und Next.js
pnpm:
  overrides:
    # Stelle sicher dass ws kompatibel mit Next.js ist
    ws: "^8.2.3"
