// firebase_functions/src/finance/types/invoice.types.ts

import { Timestamp } from 'firebase-admin/firestore';

export type InvoiceStatus =
    | 'DRAFT'           // Entwurf
    | 'PENDING'         // Bereit zum Versenden
    | 'SENT'            // Versendet
    | 'VIEWED'          // Vom Kunden angesehen
    | 'PAID'            // Bezahlt
    | 'OVERDUE'         // Überfällig
    | 'CANCELLED'       // Storniert
    | 'REFUNDED';       // Erstattet

export type InvoiceType =
    | 'STANDARD'        // Standard-Rechnung
    | 'PROFORMA'        // Proforma-Rechnung
    | 'CREDIT_NOTE'     // Gutschrift
    | 'REMINDER'        // Mahnung
    | 'CORRECTION';     // Korrektur-Rechnung

export type InvoiceSourceType =
    | 'MANUAL'          // Manuell erstellt
    | 'TASKILO_ORDER'   // Aus Taskilo-Auftrag
    | 'TIMETRACKING'    // Aus TimeTracking
    | 'RECURRING';      // Wiederkehrend

export interface InvoiceAddress {
    companyName?: string;
    firstName?: string;
    lastName?: string;
    street: string;
    postalCode: string;
    city: string;
    country: string;
    vatNumber?: string;       // USt-IdNr.
    taxNumber?: string;       // Steuernummer
}

export interface InvoiceLineItem {
    id: string;
    description: string;
    quantity: number;
    unitPrice: number;        // Nettopreis pro Einheit (in Cent)
    totalPrice: number;       // Gesamtpreis netto (in Cent)
    taxRate: number;          // Steuersatz in % (19, 7, 0)
    taxAmount: number;        // Steuerbetrag (in Cent)
    unit?: string;            // Einheit (Stunden, Stück, etc.)
    category?: string;        // Kategorie für Reporting
}

export interface InvoiceTaxSummary {
    taxRate: number;          // Steuersatz in %
    netAmount: number;        // Nettobetrag (in Cent)
    taxAmount: number;        // Steuerbetrag (in Cent)
    grossAmount: number;      // Bruttobetrag (in Cent)
}

export interface InvoicePaymentTerms {
    dueDays: number;          // Zahlungsziel in Tagen
    dueDate: Timestamp;       // Fälligkeitsdatum
    discountDays?: number;    // Skonto-Tage
    discountRate?: number;    // Skonto-Prozentsatz
    paymentMethods: string[]; // Erlaubte Zahlungsmethoden
}

export interface InvoiceSyncData {
    sourceType: InvoiceSourceType;
    sourceOrderId?: string;        // Taskilo-Auftrags-ID
    timeTrackingId?: string;       // TimeTracking-ID
    originalAmount: number;        // Ursprungsbetrag
    actualAmount: number;          // Tatsächlicher Betrag
    hoursPlanned?: number;         // Geplante Stunden
    hoursActual?: number;          // Tatsächliche Stunden
    autoGenerated: boolean;        // Automatisch generiert
    syncedAt: Timestamp;           // Synchronisationszeitpunkt
    lastSyncAt?: Timestamp;        // Letzte Synchronisation
}

export interface InvoiceData {
    // Basis-Informationen
    id: string;
    companyId: string;             // Firmen-ID
    invoiceNumber: string;         // Rechnungsnummer (GoBD-konform)

    // Status & Typ
    status: InvoiceStatus;
    type: InvoiceType;

    // Datumsangaben
    invoiceDate: Timestamp;        // Rechnungsdatum
    deliveryDate?: Timestamp;      // Lieferdatum
    serviceDate?: Timestamp;       // Leistungsdatum

    // Kunde
    customerId: string;            // Kunden-ID
    customerData: InvoiceAddress;  // Rechnungsadresse

    // Positionen
    lineItems: InvoiceLineItem[];

    // Beträge
    netAmount: number;             // Nettobetrag gesamt (in Cent)
    taxAmount: number;             // Steuerbetrag gesamt (in Cent)
    grossAmount: number;           // Bruttobetrag gesamt (in Cent)
    taxSummary: InvoiceTaxSummary[]; // Steuer-Aufschlüsselung

    // Zahlungskonditionen
    paymentTerms: InvoicePaymentTerms;

    // Synchronisation mit Taskilo
    syncData?: InvoiceSyncData;

    // Texte & Notizen
    introduction?: string;         // Einleitungstext
    conclusion?: string;           // Schlusstext
    notes?: string;               // Interne Notizen

    // Anhänge
    attachments?: string[];        // URLs zu Anhängen

    // GoBD-Compliance
    gobd: {
        archived: boolean;           // Archiviert
        immutable: boolean;          // Unveränderlich
        digitalSignature?: string;   // Digitale Signatur
        exportedAt?: Timestamp;      // Export-Zeitpunkt
    };

    // Metadaten
    createdAt: Timestamp;
    updatedAt: Timestamp;
    createdBy: string;             // User-ID
    lastModifiedBy: string;        // User-ID
}

export interface CreateInvoiceRequest {
    customerId: string;
    invoiceDate?: Timestamp;
    deliveryDate?: Timestamp;
    serviceDate?: Timestamp;
    lineItems: Omit<InvoiceLineItem, 'id' | 'totalPrice' | 'taxAmount'>[];
    introduction?: string;
    conclusion?: string;
    notes?: string;
    paymentTerms?: Partial<InvoicePaymentTerms>;
    type?: InvoiceType;
}

export interface UpdateInvoiceRequest {
    lineItems?: Omit<InvoiceLineItem, 'id' | 'totalPrice' | 'taxAmount'>[];
    introduction?: string;
    conclusion?: string;
    notes?: string;
    paymentTerms?: Partial<InvoicePaymentTerms>;
    status?: InvoiceStatus;
}

export interface InvoiceSearchFilters {
    status?: InvoiceStatus[];
    customerId?: string;
    dateFrom?: Timestamp;
    dateTo?: Timestamp;
    amountMin?: number;
    amountMax?: number;
    sourceType?: InvoiceSourceType;
    invoiceNumber?: string;
}

export interface InvoiceListResponse {
    invoices: InvoiceData[];
    total: number;
    page: number;
    limit: number;
    hasNext: boolean;
}
