// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jf9CiuvGKMK7wUw9mu-NkUIJDzoMusw',
    appId: '1:1022290879475:web:45b6e46859948ec15ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    authDomain: 'tilvo-f142f.firebaseapp.com',
    databaseURL:
        'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    measurementId: 'G-WWXT65CVC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-mx-FPoT-f2pXVP6HS_t1rE0w_eYNLY',
    appId: '1:1022290879475:android:3a621239990633c35ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    databaseURL:
        'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TN2_iDmgxjQLjkbtWFN-jhXdjRK_jIw',
    appId: '1:1022290879475:ios:b4b24626475b35f75ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    databaseURL:
        'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    iosClientId:
        '1022290879475-4k9lfpu0q44a0lafmus1ss5h25mul4um.apps.googleusercontent.com',
    iosBundleId: 'com.tilvo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_TN2_iDmgxjQLjkbtWFN-jhXdjRK_jIw',
    appId: '1:1022290879475:ios:8fd00b16c4a209de5ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    databaseURL:
        'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    iosClientId:
        '1022290879475-4fo0nm6fu4tbpe2vt09niea0er39anja.apps.googleusercontent.com',
    iosBundleId: 'com.tilvo.de',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jf9CiuvGKMK7wUw9mu-NkUIJDzoMusw',
    appId: '1:1022290879475:web:80e8212dd746085a5ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    authDomain: 'tilvo-f142f.firebaseapp.com',
    databaseURL:
        'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    measurementId: 'G-X3V12JVCLT',
  );
}
