// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-mx-FPoT-f2pXVP6HS_t1rE0w_eYNLY',
    appId: '1:1022290879475:web:3a621239990633c35ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    authDomain: 'tilvo-f142f.firebaseapp.com',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-mx-FPoT-f2pXVP6HS_t1rE0w_eYNLY',
    appId: '1:1022290879475:android:3a621239990633c35ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    databaseURL: 'https://tilvo-f142f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-mx-FPoT-f2pXVP6HS_t1rE0w_eYNLY',
    appId: '1:1022290879475:ios:3a621239990633c35ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    iosClientId: '1022290879475-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.tilvo.de',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-mx-FPoT-f2pXVP6HS_t1rE0w_eYNLY',
    appId: '1:1022290879475:ios:3a621239990633c35ae886',
    messagingSenderId: '1022290879475',
    projectId: 'tilvo-f142f',
    storageBucket: 'tilvo-f142f.firebasestorage.app',
    iosClientId: '1022290879475-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.tilvo.de',
  );
}
