import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Taskilo - Professional Service Marketplace',
  description:
    'Complete Terms of Service for Taskilo - A hybrid B2B/B2C service marketplace combining TaskRabbit, Fiverr, Malt and business management features. Read our comprehensive terms and conditions.',
  keywords: [
    'terms of service',
    'terms and conditions',
    'legal terms',
    'taskilo terms',
    'service marketplace terms',
    'B2B service terms',
    'B2C service terms',
    'platform terms',
    'user agreement',
    'service agreement',
    'freelancer terms',
    'contractor terms',
    'payment terms',
    'stripe terms',
    'platform liability',
    'dispute resolution',
    'intellectual property',
    'data protection terms',
    'GDPR compliance',
    'business terms',
    'consumer rights',
    'withdrawal rights',
    'termination terms',
    'account suspension',
    'fee structure',
    'commission rates',
    'payment processing',
    'jurisdiction',
    'applicable law',
    'cyprus law',
    'german law',
    'consumer protection',
    'business protection',
    'mediation services',
    'complaint management',
    'platform hold system',
    'escrow service',
    'secure payments',
    'trusted platform',
  ],
  openGraph: {
    title: 'Terms of Service | Taskilo',
    description:
      'Complete Terms of Service for Taskilo - Professional service marketplace with B2B/B2C solutions.',
    type: 'website',
    url: 'https://taskilo.de/terms',
    siteName: 'Taskilo',
    images: [
      {
        url: 'https://taskilo.de/images/og-terms.jpg',
        width: 1200,
        height: 630,
        alt: 'Taskilo Terms of Service',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Terms of Service | Taskilo',
    description: 'Complete Terms of Service for Taskilo - Professional service marketplace.',
    images: ['https://taskilo.de/images/og-terms.jpg'],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://taskilo.de/terms',
    languages: {
      en: 'https://taskilo.de/terms',
      de: 'https://taskilo.de/agb',
    },
  },
};
